# Generated by Django 3.1.7 on 2021-03-07 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('enrollment_number', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=200, null=True)),
                ('role', models.IntegerField(choices=[(1, 'MEMBER'), (2, 'PRESIDENT'), (3, 'VICE-PRESIDENT')], default=1)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('gender', models.CharField(choices=[(1, 'MALE'), (2, 'FEMALE'), (3, 'OTHER')], default=None, max_length=7, null=True)),
                ('course', models.CharField(choices=[(1, 'B.TECH'), (2, 'MBA')], default=None, max_length=7, null=True)),
                ('branch', models.CharField(choices=[(1, 'COMPUTER SCIENCE'), (2, 'INFORMATION TECHNOLOGY'), (3, 'ELECTRONICS AND COMMUNICATION'), (4, 'ELECTRICAL AND ELECTRONICS'), (5, 'CIVIL'), (6, 'MECHANICAL')], default=None, max_length=30, null=True)),
                ('user', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
