# Generated by Django 3.1.7 on 2021-03-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='branch',
            field=models.IntegerField(choices=[(1, 'COMPUTER SCIENCE'), (2, 'INFORMATION TECHNOLOGY'), (3, 'ELECTRONICS AND COMMUNICATION'), (4, 'ELECTRICAL AND ELECTRONICS'), (5, 'CIVIL'), (6, 'MECHANICAL')], default=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='course',
            field=models.IntegerField(choices=[(1, 'B.TECH'), (2, 'MBA')], default=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE'), (3, 'OTHER')], default=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
