# Generated by Django 3.1.7 on 2021-03-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20210314_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='enrollment_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
