MEMBER_ROLE = ((1, "MEMBER"), (2, "PRESIDENT"),(3,"VICE-PRESIDENT"))
GENDER_CHOICES = ((1, "MALE"), (2, "FEMALE"), (3, "OTHER"))
COURSE_CHOICES = ((1, "B.TECH"), (2, "MBA"))
BRANCH_CHOICES = ((1, "COMPUTER SCIENCE"), (2, "INFORMATION TECHNOLOGY"), 
(3, "ELECTRONICS AND COMMUNICATION"), (4, "ELECTRICAL AND ELECTRONICS"), (5, "CIVIL"), (6, "MECHANICAL"))